apiVersion: v1
kind: Pod
metadata:
  name: kfmysql
  namespace: kubeflow
spec:
  containers:
  - name: alpine
    image: alpine:latest
    command:
    - /bin/sh
    - -ec
    - while true; do sleep 1000; done 
    volumeMounts:
    - name: mypvc
      mountPath: /data
  volumes:
  - name: mypvc
    persistentVolumeClaim:
      claimName:  katib-mysql
