apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-kf-nfs-server-provisioner-0
spec:
  capacity:
    storage: 200Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /srv/volumes/data-kf-nfs-server-provisioner-0
  claimRef:
    namespace: kube-system
    name: data-kf-nfs-server-provisioner-0
