apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: katib-mysql
  namespace: kubeflow
  labels:
    app: katib
spec:
  storageClassName: katib
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
